services:
  db:
    image: postgres:16-alpine
    container_name: a_bingo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bingo_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bingo_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - a_bingo_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: a_bingo_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: a_bingo_backend
    restart: always
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/bingo_db
      - REDIS_URL=redis://redis:6379/0
      - BOT_TOKEN=8990850541:AAGFCIi6qLtQydYp7q4DyHZHqnO-3VrF3pg
      - SECRET_KEY=dev_super_secret_jwt_hmac_key_bingo_telegram_2026_9999
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  a_bingo_postgres_data:
